apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-build
spec:
  description: | 
    This pipeline builds a Docker image with Kaniko and pushes it to a registry.
  params:
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: create-dockerfile
    taskSpec:
      workspaces:
      - name: shared-data
      steps:
      - name: create-dockerfile
        workingDir: "$(workspaces.shared-data.path)"
        image: gcr.io/kaniko-project/debug:769
        script: |
          #!/busybox/sh
          set -e
          /busybox/cat > Dockerfile <<EOF
          FROM alpine
          CMD tail -f /dev/null
          EOF
    workspaces:
    - name: shared-data
  - name: build-push
    runAfter: ["create-dockerfile"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: $(params.image-reference)

