apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: simple-build-run-
spec:
  pipelineRef:
    name: simple-build
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: image-reference
