apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: simple-build-run-
spec:
  taskRef:
    name: simple-build
  workspaces:
  - name: working-dir
    emptyDir: {}
  params:
  - name: IMAGE
